// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkflowDemo.WebUI.Entities;

namespace WorkflowDemo.WebUI.Migrations
{
    [DbContext(typeof(WorkflowDemoContext))]
    [Migration("20190701122529_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WorkflowDemo.WebUI.Entities.AuditLog", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50);

                    b.Property<string>("ActionName")
                        .HasMaxLength(255);

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255);

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(255);

                    b.Property<DateTime?>("DeletedOn");

                    b.Property<string>("Description")
                        .HasMaxLength(1000);

                    b.Property<int>("Duration");

                    b.Property<string>("ExceptionContent");

                    b.Property<string>("Ip")
                        .HasMaxLength(255);

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("RequestParam")
                        .HasMaxLength(10000);

                    b.Property<string>("RequestUrl")
                        .HasMaxLength(1000);

                    b.Property<string>("ResponseParam");

                    b.Property<string>("ServiceName")
                        .HasMaxLength(255);

                    b.Property<int>("Type");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255);

                    b.Property<DateTime?>("UpdatedOn");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(1000);

                    b.HasKey("Id");

                    b.ToTable("AuditLog");
                });

            modelBuilder.Entity("WorkflowDemo.WebUI.Entities.FlowScheme", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50);

                    b.Property<int>("AuthorizeType");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255);

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(255);

                    b.Property<DateTime?>("DeletedOn");

                    b.Property<string>("Description");

                    b.Property<int>("Disabled");

                    b.Property<string>("FrmId");

                    b.Property<int>("FrmType");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("SchemeCode");

                    b.Property<string>("SchemeContent");

                    b.Property<string>("SchemeName");

                    b.Property<string>("SchemeType");

                    b.Property<string>("SchemeVersion");

                    b.Property<int>("SortCode");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255);

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("Id");

                    b.ToTable("FlowScheme");
                });

            modelBuilder.Entity("WorkflowDemo.WebUI.Entities.Function", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ChineseGroup")
                        .HasMaxLength(255);

                    b.Property<string>("ChineseName")
                        .HasMaxLength(1000);

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255);

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(255);

                    b.Property<DateTime?>("DeletedOn");

                    b.Property<string>("Description")
                        .HasMaxLength(1000);

                    b.Property<string>("Group")
                        .HasMaxLength(255);

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name")
                        .HasMaxLength(255);

                    b.Property<int>("Position");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255);

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("Id");

                    b.ToTable("Function");
                });

            modelBuilder.Entity("WorkflowDemo.WebUI.Entities.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ChineseTitle")
                        .HasMaxLength(255);

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255);

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(255);

                    b.Property<DateTime?>("DeletedOn");

                    b.Property<int?>("FunctionId");

                    b.Property<string>("Icon")
                        .HasMaxLength(255);

                    b.Property<bool>("IsDeleted");

                    b.Property<int?>("ParentId");

                    b.Property<int>("Position");

                    b.Property<string>("Title")
                        .HasMaxLength(255);

                    b.Property<bool>("Unlinked");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255);

                    b.Property<DateTime?>("UpdatedOn");

                    b.Property<string>("Url")
                        .HasMaxLength(1000);

                    b.HasKey("Id");

                    b.HasIndex("FunctionId");

                    b.HasIndex("ParentId");

                    b.ToTable("Menu");
                });

            modelBuilder.Entity("WorkflowDemo.WebUI.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255);

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(255);

                    b.Property<DateTime?>("DeletedOn");

                    b.Property<string>("Description")
                        .HasMaxLength(1000);

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name")
                        .HasMaxLength(255);

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255);

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("Id");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("WorkflowDemo.WebUI.Entities.RoleFunction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255);

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(255);

                    b.Property<DateTime?>("DeletedOn");

                    b.Property<int?>("FunctionId");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("RoleId");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255);

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("Id");

                    b.HasIndex("FunctionId");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleFunction");
                });

            modelBuilder.Entity("WorkflowDemo.WebUI.Entities.RoleUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255);

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(255);

                    b.Property<DateTime?>("DeletedOn");

                    b.Property<bool>("IsDeleted");

                    b.Property<int?>("RoleId");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255);

                    b.Property<DateTime?>("UpdatedOn");

                    b.Property<int?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("RoleUser");
                });

            modelBuilder.Entity("WorkflowDemo.WebUI.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255);

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(255);

                    b.Property<DateTime?>("DeletedOn");

                    b.Property<string>("EmployeeNo")
                        .HasMaxLength(255);

                    b.Property<DateTime?>("ExpirationDate");

                    b.Property<string>("FirstName")
                        .HasMaxLength(255);

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Mail")
                        .HasMaxLength(255);

                    b.Property<string>("MobileNo")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(255);

                    b.Property<string>("Password")
                        .HasColumnType("VARCHAR(255)");

                    b.Property<string>("PasswordSalt")
                        .HasColumnType("VARCHAR(255)");

                    b.Property<string>("PhoneNo")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("PlantId")
                        .HasMaxLength(50);

                    b.Property<string>("SecondName")
                        .HasMaxLength(255);

                    b.Property<int>("Status");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255);

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("WorkflowDemo.WebUI.Entities.Menu", b =>
                {
                    b.HasOne("WorkflowDemo.WebUI.Entities.Function", "Function")
                        .WithMany("Menu")
                        .HasForeignKey("FunctionId");

                    b.HasOne("WorkflowDemo.WebUI.Entities.Menu", "Parent")
                        .WithMany("InverseParent")
                        .HasForeignKey("ParentId");
                });

            modelBuilder.Entity("WorkflowDemo.WebUI.Entities.RoleFunction", b =>
                {
                    b.HasOne("WorkflowDemo.WebUI.Entities.Function", "Function")
                        .WithMany("RoleFunction")
                        .HasForeignKey("FunctionId");

                    b.HasOne("WorkflowDemo.WebUI.Entities.Role", "Role")
                        .WithMany("RoleFunction")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WorkflowDemo.WebUI.Entities.RoleUser", b =>
                {
                    b.HasOne("WorkflowDemo.WebUI.Entities.Role", "Role")
                        .WithMany("RoleUser")
                        .HasForeignKey("RoleId");

                    b.HasOne("WorkflowDemo.WebUI.Entities.User", "User")
                        .WithMany("RoleUser")
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
